spring:
  application:
    name: remote-motor-monitoring
  datasource:
    url: jdbc:mysql://localhost:3306/motor_monitoring
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Tafadzwa@25'
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/RemoteMonitoring
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  mail:
    host: smtp.gmail.com
    port: 587
    username: muunganitafadzwa25@gmail.com
    password: 'yupyxufvwrmxlmxv'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8025

twilio:
  account:
    sid: ACd21eef2c501e57e306855cd7ca711890
    authToken: 6433695c72e38ce5c4b6cc41ee577360
    number: +19386666588
    test: +263713384934

keycloak:
  client-id: backend
  client-secret: 9fbvCQ54cJZsUMBRWFLfy0Sge7lR8VRv
  grant_type: password
  token-uri: http://localhost:8080/realms/RemoteMonitoring/protocol/openid-connect/token

jwt:
  auth:
    converter:
      resource-id: backend
      principle-attribute: preferred_username,

email:
  from: muunganitafadzwa25@gmail.com
  fromName: Remote Motor Monitoring
  to: whitethatboy@gmail.com

clickatel:
  http:
    api:
      key: "-iUqtrnATD6WD_ExVgXlVg==
"
    send:
      url: 'https://platform.clickatell.com/messages/http/send?apiKey={apiKey}&to={to}&content={content}'